name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Build, Test and Publish NuGet Package
      run: |
        dotnet build -c Release
        dotnet test -c Release --no-build
        dotnet pack -c Release /p:PackageVersion=${{ steps.gitversion.outputs.semVer }} --no-build
        dotnet nuget push ./src/CQSDotnet.Autofac/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
